services:
  minip:
    image: mini/mini
    container_name: mini-server
    ports:
      - "9000:9000" # Port API cho app kết nối
      - "9001:9001" # Port Giao diện Web (Console)
    environment:
        MINIO_ROOT_USER: "admin"
        MINIO_ROOT_PASSWORD: "password123"
    volumes:
        # Dòng này giữ ảnh an toàn! Dữ liệu được lưu vào thư mục minio_data trên máy thật
        - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data: # Khai báo volume cố định
